//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KITT.Proposals.Web.App.Resources.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KITT.Proposals.Web.App.Resources.Pages.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re going to accept the proposal {0}. Are you sure?.
        /// </summary>
        internal static string AcceptProposalConfirmText {
            get {
                return ResourceManager.GetString("AcceptProposalConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept this proposal.
        /// </summary>
        internal static string AcceptProposalConfirmTitle {
            get {
                return ResourceManager.GetString("AcceptProposalConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error accepting the proposal {0}.
        /// </summary>
        internal static string AcceptProposalErrorMessage {
            get {
                return ResourceManager.GetString("AcceptProposalErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The proposal {0} has been accepted successfully!.
        /// </summary>
        internal static string AcceptProposalSuccessMessage {
            get {
                return ResourceManager.GetString("AcceptProposalSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Older.
        /// </summary>
        internal static string Ascending {
            get {
                return ResourceManager.GetString("Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newer.
        /// </summary>
        internal static string Descending {
            get {
                return ResourceManager.GetString("Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderating.
        /// </summary>
        internal static string Moderating {
            get {
                return ResourceManager.GetString("Moderating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There aren&apos;t any proposals loaded. Please try with some different search terms.
        /// </summary>
        internal static string NoProposalsMessage {
            get {
                return ResourceManager.GetString("NoProposalsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage the proposals.
        /// </summary>
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string ProposalAcceptLabel {
            get {
                return ResourceManager.GetString("ProposalAcceptLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author nickname.
        /// </summary>
        internal static string ProposalAuthorLabel {
            get {
                return ResourceManager.GetString("ProposalAuthorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string ProposalDateLabel {
            get {
                return ResourceManager.GetString("ProposalDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string ProposalDescriptionLabel {
            get {
                return ResourceManager.GetString("ProposalDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refuse.
        /// </summary>
        internal static string ProposalRefuseLabel {
            get {
                return ResourceManager.GetString("ProposalRefuseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        internal static string ProposalRejectLabel {
            get {
                return ResourceManager.GetString("ProposalRejectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        internal static string ProposalScheduleLabel {
            get {
                return ResourceManager.GetString("ProposalScheduleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string ProposalSearchLabel {
            get {
                return ResourceManager.GetString("ProposalSearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string ProposalsQueryOrderLabel {
            get {
                return ResourceManager.GetString("ProposalsQueryOrderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for....
        /// </summary>
        internal static string ProposalsQuerySearchLabel {
            get {
                return ResourceManager.GetString("ProposalsQuerySearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr. of elements.
        /// </summary>
        internal static string ProposalsQuerySizeLabel {
            get {
                return ResourceManager.GetString("ProposalsQuerySizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string ProposalStatusLabel {
            get {
                return ResourceManager.GetString("ProposalStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string ProposalTitleLabel {
            get {
                return ResourceManager.GetString("ProposalTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re going to refuse the proposal {0}. Are you sure?.
        /// </summary>
        internal static string RefuseProposalConfirmText {
            get {
                return ResourceManager.GetString("RefuseProposalConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refuse this proposal.
        /// </summary>
        internal static string RefuseProposalConfirmTitle {
            get {
                return ResourceManager.GetString("RefuseProposalConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error refusing the proposal {0}.
        /// </summary>
        internal static string RefuseProposalErrorMessage {
            get {
                return ResourceManager.GetString("RefuseProposalErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The proposal {0} has been refused successfully!.
        /// </summary>
        internal static string RefuseProposalSuccessMessage {
            get {
                return ResourceManager.GetString("RefuseProposalSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re going to reject the proposal {0}. Are you sure?.
        /// </summary>
        internal static string RejectProposalConfirmText {
            get {
                return ResourceManager.GetString("RejectProposalConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject this proposal.
        /// </summary>
        internal static string RejectProposalConfirmTitle {
            get {
                return ResourceManager.GetString("RejectProposalConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error rejecting the proposal {0}.
        /// </summary>
        internal static string RejectProposalErrorMessage {
            get {
                return ResourceManager.GetString("RejectProposalErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The proposal {0} has been rejected successfully!.
        /// </summary>
        internal static string RejectProposalSuccessMessage {
            get {
                return ResourceManager.GetString("RejectProposalSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string ShowProposalDetailLabel {
            get {
                return ResourceManager.GetString("ShowProposalDetailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for approval.
        /// </summary>
        internal static string WaitingForApproval {
            get {
                return ResourceManager.GetString("WaitingForApproval", resourceCulture);
            }
        }
    }
}
