<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Azure.Security.KeyVault" Version="13.4.6" />
    <PackageReference Include="AzureKeyVaultEmulator.Client" Version="3.1.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.10" />
    <PackageReference Include="Microsoft.Identity.Web" Version="4.13.2" />
  </ItemGroup>

</Project>
